# Generated by Django 5.2.7 on 2025-10-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите марку автомобиля', max_length=30, verbose_name='Марка автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='CarNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название региона', max_length=100, verbose_name='Название региона')),
                ('number', models.CharField(help_text='Введите номер региона', max_length=3, verbose_name='Номер региона')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название роли', max_length=30, verbose_name='Название роли')),
                ('description', models.CharField(blank=True, help_text='Введите описание роли', max_length=100, null=True, verbose_name='Описание роли')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите модель автомобиля', max_length=50, verbose_name='Модель автомобиля')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_number', models.CharField(max_length=17)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.carbrand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.carmodel')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.carnumber')),
            ],
        ),
        migrations.AddField(
            model_name='carnumber',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.region'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(help_text='Введите имя', max_length=100, verbose_name='Имя')),
                ('fatherName', models.CharField(blank=True, help_text='Введите отчество', max_length=100, null=True, verbose_name='Отчество')),
                ('dateOfBirth', models.DateField(help_text='Введите дату рождения', verbose_name='Дата рождения')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.role')),
            ],
        ),
        migrations.CreateModel(
            name='ContactHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_number', models.CharField(max_length=5)),
                ('contract', models.FileField(blank=True, help_text='Загрузите договор о куплепродажи', null=True, upload_to='contract/', verbose_name='Договор о куплепродажи')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.car')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_histories_as_buyer', to='web.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_histories_as_owner', to='web.user')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.user'),
        ),
    ]
